services:
    CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\SimpleFieldComparator:
        parent: 'CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\AbstractFieldComparator'
        tags:
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezauthor' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezboolean' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezcountry' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezdate' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezdatetime' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezemail' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezfloat' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezinteger' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezisbn' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezkeyword' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezobjectrelation' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezobjectrelationlist' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezrichtext' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezselection' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'eztext' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezstring' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'eztime' }
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'eztags' }

    CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\UrlFieldComparator:
        parent: 'CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\AbstractFieldComparator'
        tags:
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezurl' }

    CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\NovaSEOMetasFieldComparator:
        parent: 'CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\AbstractFieldComparator'
        tags:
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'novaseometas' }

    CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\MatrixFieldComparator:
        parent: 'CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\AbstractFieldComparator'
        tags:
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezmatrix' }

    CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\MapLocationFieldComparator:
        parent: 'CodeRhapsodie\IbexaDataflowBundle\Core\FieldComparator\AbstractFieldComparator'
        tags:
            - { name: 'coderhapsodie.ibexa_dataflow.field_comparator', fieldType: 'ezgmaplocation' }
